<#if !noDefaultComment>
    /**
    * Code generated by unionj-generator-mybatis. DO NOT EDIT.
    * https://github.com/unionj-cloud/unionj-generator
    */

</#if>package ${packageName};

import cn.hutool.core.util.StrUtil;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import uk.co.jemos.podam.api.PodamFactory;
import uk.co.jemos.podam.api.PodamFactoryImpl;
import lombok.extern.slf4j.Slf4j;
<#if imports??>
    <#list imports as import>
        import ${import};
    </#list>
</#if>

@Slf4j
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {${mainClassName}.class})
public class ${mapperName}Test {

    @Autowired
    private ${mapperName} mapper;

    <#list methods as method>
        <#compress>@Test
            public void ${method.methodName}() {
                <#if method.parameters??>
                    PodamFactory factory = new PodamFactoryImpl();
                    <#assign params=[]>
                    <#list method.parameters as parameter>
                        ${parameter.fullType} arg${parameter?index} = factory.manufacturePojo(<#list parameter.types as atype><#if !atype?is_first>, </#if>${atype}.class</#list>);
                        <#assign params = params + [ "arg${parameter?index}" ] />
                        log.debug(StrUtil.format("{}", arg${parameter?index}));
                    </#list>
                    mapper.${method.methodName}(<#list params as param><#if !param?is_first>, </#if>${param}</#list>);
                <#else>
                    mapper.${method.methodName}();
                </#if>
            }</#compress>
        <#sep>

        </#sep>
    </#list>
}
