/**
* Generated by unionj-generator.
* You can edit it as your need.
*/
import { merge } from 'lodash-es';
import { CreateAxiosOptions, VAxios } from 'pullcode/src/httputil/Axios';

const defaultOptions = {
  requestOptions: {
    apiUrl: "http://www.unionj.com",
  },
}

export class BizService extends VAxios {
  constructor(options?: Partial<CreateAxiosOptions>) {
    super(merge(defaultOptions, options || {}));
  }
}

export default BizService;

