/**
* Generated by unionj-generator.
* Don't edit!
*
* @module 材料申报模块
*/
import { CreateAxiosOptions } from "pullcode/src/httputil/axiosTransform";
import BizService from "./BizService";
import type {
  PostClshenbaoFormSavePayload,
  SearchJobPageResult,
} from "./types"

export class ClshenbaoFormService extends BizService{

  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
  * POST /clshenbao/form/save
  *
  * 材料申报：保存form表单
  * @param payload 这是payload
  * @param key 键
  * @param style 样式
  * @returns Promise<SearchJobPageResult> 返回参数
  */
  postClshenbaoFormSave(
    payload: PostClshenbaoFormSavePayload,
    params: {
      key: string,
      style?: string,
    },
  ) :Promise<SearchJobPageResult> {
    return this.getAxios().post(`/clshenbao/form/save`,
          payload,
          {
            params: {
              key: params.key,
              style: params.style,
            },
          }
        )
  }

}

export default ClshenbaoFormService;
  
export function createClshenbaoFormService(opt?: Partial<CreateAxiosOptions>) {
  return new ClshenbaoFormService(opt);
}

export const clshenbaoFormService = createClshenbaoFormService();

