/**
* Generated by unionj-generator.
* Don't edit!
*
* @module Logout
*/
import { CreateAxiosOptions } from "pullcode/src/httputil/axiosTransform";
import BizService from "./BizService";
import type {
  GetLogoutResp,
} from "./types"

export class LogoutService extends BizService{

  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
  * GET /logout
  *
  * GetLogout ×¢Ïútoken
  * GetLogout is used for revoking a token
  * https://github.com/dgrijalva/jwt-go/issues/214
  * @returns Promise<GetLogoutResp> 
  */
  getLogout(
  ) :Promise<GetLogoutResp> {
    return this.getAxios().get(`/logout`,
          {
          }
        )
  }

}

export default LogoutService;
  
export function createLogoutService(opt?: Partial<CreateAxiosOptions>) {
  return new LogoutService(opt);
}

export const logoutService = createLogoutService();

