/**
* Generated by unionj-generator.
* Don't edit!
*
* @module Me
*/
import { CreateAxiosOptions } from "pullcode/src/httputil/axiosTransform";
import BizService from "./BizService";
import type {
  GetMeResp,
} from "./types"

export class MeService extends BizService{

  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
  * GET /me
  *
  * GetMe 获取当前登录用户详情接口
  * GetMe is used for getting user info from token in header.
  * @returns Promise<GetMeResp> 
  */
  getMe(
  ) :Promise<GetMeResp> {
    return this.getAxios().get(`/me`,
          {
          }
        )
  }

}

export default MeService;
  
export function createMeService(opt?: Partial<CreateAxiosOptions>) {
  return new MeService(opt);
}

export const meService = createMeService();

