/**
* Generated by unionj-generator.
* Don't edit!
*
* @module Me
*/
import BizService from "./BizService";
import type {
  GetMeResp,
} from "./types"

export class MeService extends BizService{

  constructor(axios: any) {
    super(axios);
  }

  /**
  * GET /me
  *
  * GetMe 获取当前登录用户详情接口
  * GetMe is used for getting user info from token in header.
  * @returns Promise<GetMeResp> 
  */
  getMe(
  ) :Promise<GetMeResp> {
    let client = this.axios.get
    if(this.axios.$get) {
      client = this.axios.$get
    }
    return client(this.addPrefix(`/me`),
          {
          }
        )
  }

}

export default MeService;

