/**
* Generated by unionj-generator.
* Don't edit!
*
* @module Attachment
*/
import BizService from "./BizService";
import type {
  ResultDTOString,
} from "./types"

export class OssService extends BizService{

  constructor(axios: any) {
    super(axios);
  }

  /**
  * POST /oss/upload
  *
  * 上传附件
  * @param formData 
  * @param returnKey 
  * @returns Promise<ResultDTOString> 
  */
  postOssUpload(
    formData: FormData,
    params: {
      returnKey?: boolean,
    },
  ) :Promise<ResultDTOString> {
    let client = this.axios.post
    if(this.axios.$post) {
      client = this.axios.$post
    }
    return client(this.addPrefix(`/oss/upload`),
          formData,
          {
            params: {
              returnKey: params.returnKey,
            },
          }
        )
  }

  /**
  * GET /oss/get
  *
  * 获取附件
  * @param key 
  * @param style 
  * @returns Promise<any> 
  */
  getOssGet(
    params: {
      key: string,
      style?: string,
    },
  ) :Promise<any> {
    let client = this.axios.get
    if(this.axios.$get) {
      client = this.axios.$get
    }
    return client(this.addPrefix(`/oss/get`),
          {
            params: {
              key: params.key,
              style: params.style,
            },
            responseType: 'blob',
          }
        )
  }

}

export default OssService;

