/**
* Generated by unionj-generator.
* Don't edit!
*
* @module Page
*/
import BizService from "./BizService";
import type {
  PageQuery,
  PageUsersResp,
} from "./types"

export class PageService extends BizService{

  constructor(axios: any) {
    super(axios);
  }

  /**
  * POST /page/users
  *
  * PageUsers 用户分页接口
  * 展示如何定义POST请求且Content-Type为application/json的接口
  * PageUsers is user pagination api
  * demo how to define post request api which accepts application/json content-type
  * @param payload 
  * @returns Promise<PageUsersResp> 
  */
  postPageUsers(
    payload: PageQuery,
  ) :Promise<PageUsersResp> {
    let client = this.axios.post
    if(this.axios.$post) {
      client = this.axios.$post
    }
    return client(this.addPrefix(`/page/users`),
          payload,
          {
          }
        )
  }

}

export default PageService;

