/**
* Generated by unionj-generator.
* Don't edit!
*
* @module Page
*/
import { CreateAxiosOptions } from "pullcode/src/httputil/axiosTransform";
import BizService from "./BizService";
import type {
  PageQuery,
  PageUsersResp,
} from "./types"

export class PageService extends BizService{

  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
  * POST /page/users
  *
  * PageUsers 用户分页接口
  * 展示如何定义POST请求且Content-Type为application/json的接口
  * PageUsers is user pagination api
  * demo how to define post request api which accepts application/json content-type
  * @param payload 
  * @returns Promise<PageUsersResp> 
  */
  postPageUsers(
    payload: PageQuery,
  ) :Promise<PageUsersResp> {
    return this.getAxios().post(`/page/users`,
          payload,
          {
          }
        )
  }

}

export default PageService;
  
export function createPageService(opt?: Partial<CreateAxiosOptions>) {
  return new PageService(opt);
}

export const pageService = createPageService();

