/**
* Generated by unionj-generator.
* Don't edit!
* @module types
*/

export interface User {
    name: string;
    info: any;
}


export interface UserInteger {
    name: string;
    info: number;
}


export interface ResultDTOSetUserDate {
    msg: string;
    code: number;
    data: UserDate[];
}


export interface ResultDTOSetUserInteger {
    msg: string;
    code: number;
    data: UserInteger[];
}


export interface ShopRecommendApplyDetailCondition {
    /**
    * 总数，入参传入此参数则不再查询count，以此total为准
    */
    total: number;
    /**
    * 当前页，从1开始
    */
    current: number;
    /**
    * 每页条数，默认10，传-1查出全部数据
    */
    size: number;
    /**
    * 偏移量
    */
    offset: number;
    /**
    * 需要排在前的状态
    */
    topStatus: number;
    /**
    * 每页条数，默认10, 传-1查出全部数据
    */
    limit: number;
    /**
    * 店铺名称
    */
    shopName: string;
    /**
    * 当前页，从1开始
    */
    page: number;
    /**
    * 排序条件字符串：排序字段前使用'-'(降序)和'+'(升序)号表示排序规则，多个排序字段用','隔开
    */
    sort: string;
    /**
    * 导出结束页
    */
    maxPage: number;
    /**
    * 审批状态
    */
    status: number[];
}


export interface UserDate {
    name: string;
    info: string;
}


export interface ResultDTO {
    msg: string;
    code: number;
    data: any;
}


export interface FuzzySearchRequestVO {
    keyword: string;
    /**
    * 城市
    */
    type: FuzzySearchRequestVOTypeEnum;
}

export enum FuzzySearchRequestVOTypeEnum {
    北京 = "北京",
    上海 = "上海",
    广州 = "广州",
    深圳 = "深圳",
}

