/**
* Generated by unionj-generator.
* Don't edit!
*
* @module Upload
*/
import { CreateAxiosOptions } from "pullcode/src/httputil/axiosTransform";
import BizService from "./BizService";
import type {
  UploadAvatarResp,
} from "./types"

export class UploadService extends BizService{

  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
  * POST /upload/avatar
  *
  * UploadAvatar 上传头像接口
  * 展示如何定义文件上传接口
  * 函数签名的入参里必须要有至少一个[]*v3.FileModel或者*v3.FileModel类型的参数
  * UploadAvatar is avatar upload api
  * demo how to define file upload api
  * NOTE: there must be at least one []*v3.FileModel or *v3.FileModel input parameter
  * @param formData 
  * @returns Promise<UploadAvatarResp> 
  */
  postUploadAvatar(
    formData: FormData,
  ) :Promise<UploadAvatarResp> {
    return this.getAxios().post(`/upload/avatar`,
          formData,
          {
          }
        )
  }

}

export default UploadService;
  
export function createUploadService(opt?: Partial<CreateAxiosOptions>) {
  return new UploadService(opt);
}

export const uploadService = createUploadService();

