/**
* Generated by unionj-generator.
* Don't edit!
*
* @module Userservice
*/
import BizService from "./BizService";
import type {
  LogInForm,
  PageQuery,
  SignUpForm,
  Auth,
  PageRet,
  UserVo,
} from "./types"

export class UserserviceService extends BizService{

  constructor(axios: any) {
    super(axios);
  }

  /**
  * POST /userservice/login
  *
  * @param payload 
  * @returns Promise<Auth> 
  */
  postUserserviceLogin(
    payload: LogInForm,
  ) :Promise<Auth> {
    let client = this.axios.post
    if(this.axios.$post) {
      client = this.axios.$post
    }
    return client(this.addPrefix(`/userservice/login`),
          payload,
        )
  }

  /**
  * POST /userservice/pageusers
  *
  * @param payload 
  * @returns Promise<PageRet> 
  */
  postUserservicePageusers(
    payload: PageQuery,
  ) :Promise<PageRet> {
    let client = this.axios.post
    if(this.axios.$post) {
      client = this.axios.$post
    }
    return client(this.addPrefix(`/userservice/pageusers`),
          payload,
        )
  }

  /**
  * POST /userservice/signup
  *
  * @param payload 
  * @returns Promise<number> 
  */
  postUserserviceSignup(
    payload: SignUpForm,
  ) :Promise<number> {
    let client = this.axios.post
    if(this.axios.$post) {
      client = this.axios.$post
    }
    return client(this.addPrefix(`/userservice/signup`),
          payload,
        )
  }

  /**
  * GET /userservice/user/${params.b}/${params.id}
  *
  * @param c 
  * @param d 
  * @param id 
  * @param a 
  * @param b 
  * @param e 
  * @param f 
  * @returns Promise<UserVo> 
  */
  getUserserviceUserParamsBParamsId(
    params: {
      c: number,
      d: number,
      id?: number,
      a?: number,
      b?: number,
      e?: number,
      f?: number,
    },
  ) :Promise<UserVo> {
    let client = this.axios.get
    if(this.axios.$get) {
      client = this.axios.$get
    }
    return client(this.addPrefix(`/userservice/user/${params.b}/${params.id}`),
          {
            params: {
              a: params.a,
              c: params.c,
              d: params.d,
              e: params.e,
              f: params.f,
            },
          }
        )
  }

}

export default UserserviceService;

