/**
* Generated by unionj-generator.
* Don't edit!
*
* @module User
*/
import BizService from "./BizService";
import type {
  GetUserResp,
} from "./types"

export class UserService extends BizService{

  constructor(axios: any) {
    super(axios);
  }

  /**
  * GET /user
  *
  * GetUser 用户详情接口
  * 展示如何定义带查询字符串参数的GET请求接口
  * GetUser is user detail api
  * demo how to define get http request with query string parameters
  * @param userId 用户ID
user id
  * @returns Promise<GetUserResp> 
  */
  getUser(
    params: {
      userId: number,
    },
  ) :Promise<GetUserResp> {
    let client = this.axios.get
    if(this.axios.$get) {
      client = this.axios.$get
    }
    return client(this.addPrefix(`/user`),
          {
            params: {
              userId: params.userId,
            },
          }
        )
  }

}

export default UserService;

