/**
* Generated by unionj-generator.
* Don't edit!
*
* @module User
*/
import { CreateAxiosOptions } from "pullcode/src/httputil/axiosTransform";
import BizService from "./BizService";
import type {
  GetUserResp,
} from "./types"

export class UserService extends BizService{

  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
  * GET /user
  *
  * GetUser 用户详情接口
  * 展示如何定义带查询字符串参数的GET请求接口
  * GetUser is user detail api
  * demo how to define get http request with query string parameters
  * @param userId 用户ID
user id
  * @returns Promise<GetUserResp> 
  */
  getUser(
    params: {
      userId: number,
    },
  ) :Promise<GetUserResp> {
    return this.getAxios().get(`/user`,
          {
            params: {
              userId: params.userId,
            },
          }
        )
  }

}

export default UserService;
  
export function createUserService(opt?: Partial<CreateAxiosOptions>) {
  return new UserService(opt);
}

export const userService = createUserService();

