/**
* Generated by unionj-generator.
* Don't edit!
*
* @module Userservice
*/
import { CreateAxiosOptions } from "pullcode/src/httputil/axiosTransform";
import BizService from "./BizService";
import type {
  LogInForm,
  PageQuery,
  SignUpForm,
  Auth,
  PageRet,
  UserVo,
} from "./types"

export class UserserviceService extends BizService{

  constructor(options?: Partial<CreateAxiosOptions>) {
    super(options);
  }

  /**
  * POST /userservice/login
  *
  * @param payload 
  * @returns Promise<Auth> 
  */
  postUserserviceLogin(
    payload: LogInForm,
  ) :Promise<Auth> {
    return this.getAxios().post(`/userservice/login`,
          payload,
          {
          }
        )
  }

  /**
  * POST /userservice/pageusers
  *
  * @param payload 
  * @returns Promise<PageRet> 
  */
  postUserservicePageusers(
    payload: PageQuery,
  ) :Promise<PageRet> {
    return this.getAxios().post(`/userservice/pageusers`,
          payload,
          {
          }
        )
  }

  /**
  * POST /userservice/signup
  *
  * @param payload 
  * @returns Promise<number> 
  */
  postUserserviceSignup(
    payload: SignUpForm,
  ) :Promise<number> {
    return this.getAxios().post(`/userservice/signup`,
          payload,
          {
          }
        )
  }

  /**
  * GET /userservice/user/${params.b}/${params.id}
  *
  * @param c 
  * @param d 
  * @param id 
  * @param a 
  * @param b 
  * @param e 
  * @param f 
  * @returns Promise<UserVo> 
  */
  getUserserviceUserParamsBParamsId(
    params: {
      c: number,
      d: number,
      id?: number,
      a?: number,
      b?: number,
      e?: number,
      f?: number,
    },
  ) :Promise<UserVo> {
    return this.getAxios().get(`/userservice/user/${params.b}/${params.id}`,
          {
            params: {
              a: params.a,
              c: params.c,
              d: params.d,
              e: params.e,
              f: params.f,
            },
          }
        )
  }

}

export default UserserviceService;
  
export function createUserserviceService(opt?: Partial<CreateAxiosOptions>) {
  return new UserserviceService(opt);
}

export const userserviceService = createUserserviceService();

