/**
* Generated by unionj-generator.
*/
import type { NuxtAxiosInstance } from "@nuxtjs/axios";

export default class BizService {

  static serverName: string | undefined = "${serverName!}";

  axios: NuxtAxiosInstance;

  constructor(axios: NuxtAxiosInstance) {
    this.axios = axios;
  }

  protected addPrefix(endpoint: string){
    if(BizService.serverName) {
      if(BizService.serverName.startsWith("/")) {
        return BizService.serverName + endpoint
      }
      return "/" + BizService.serverName + endpoint
    }
    return endpoint
  }

}
