<#if !noDefaultComment>
/**
* Code generated by unionj-generator-maven-plugin. DO NOT EDIT.
* https://github.com/unionj-cloud/unionj-generator
*/

</#if>package ${packageName};

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.cloud.openfeign.FeignClient;
import java.util.*;
import ${voPackageName}.*;
<#if imports??>
    <#list imports as import>
import ${import};
    </#list>
</#if>

/**
* @ProductName: ${companyName} ${parentArtifactId}
* @Description: ${serviceId}服务${baseName}模块REST接口Openfeign客户端
* @Author: ${author}
* @CreateDate: ${createDate}
* @Version: ${parentVersion}
* @Copyright © ${year} ${copyright}
*/
@FeignClient(contextId = "${name?uncap_first}", value = "${serviceId}"<#if serviceBaseUrlKey??>, url = "${r"${"}${serviceBaseUrlKey}${r":}"}"</#if>)
public interface ${name} {

    <#list routers as router>
    @${router.httpMethod?capitalize}Mapping("${router.endpoint}")
    ${router.respData.type} ${router.name}(
        <#assign x>
            <#if router.pathParams??>
                <#list router.pathParams as pathParam>
        <#if pathParam.required>@PathVariable("${pathParam.name}")<#else>@PathVariable(value="${pathParam.name}", required=false)</#if> ${pathParam.type} ${pathParam.name},
                </#list>
            </#if>
            <#if router.queryParams??>
                <#list router.queryParams as queryParam>
        <#if queryParam.required>@RequestParam("${queryParam.requestParam}")<#elseif queryParam.defaultValue??>@RequestParam(value="${queryParam.requestParam}", required=false, defaultValue="${queryParam.defaultValue}")<#else>@RequestParam(value="${queryParam.requestParam}", required=false)</#if> ${queryParam.type} ${queryParam.name},
                </#list>
            </#if>
            <#if router.reqBody??>
        <#if router.reqBody.required>@RequestBody<#else>@RequestBody(required=false)</#if> ${router.reqBody.type} ${router.reqBody.name},
            </#if>
            <#if router.file??>
        <#if router.file.required>@RequestPart("${router.file.name}")<#else>@RequestPart(value="${router.file.name}", required=false)</#if> ${router.file.type} ${router.file.name},
            </#if>
        </#assign>
        ${x?keep_before_last(",")?trim}
    );
    <#sep>

    </#sep>
    </#list>

}
