<#if !noDefaultComment>
/**
 * Code generated by unionj-generator-maven-plugin. DO NOT EDIT.
 * https://github.com/unionj-cloud/unionj-generator
*/

</#if>package ${packageName};

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.util.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import ${voPackageName}.*;
<#if imports??>
    <#list imports as import>
import ${import};
    </#list>
</#if>

/**
 * @ProductName: ${companyName} ${parentArtifactId} <br>
 * @Description: ${baseName}模块控制层接口类 <br>
 * @Author: ${author} <br>
 * @CreateDate: ${createDate} <br>
 * @Version: ${parentVersion} <br>
 * @Copyright © ${year} ${copyright} <br>
*/
@Tag(name = "${baseName}模块接口")
<#if base??>
@RequestMapping("${base}")
</#if>
public interface ${name} {

    <#list routers as router>
    <#compress>
    @Operation(summary = "${router.summary!""}", description = "${router.description!""}")
    @${router.httpMethod?capitalize}Mapping("${router.endpoint}")
    ${router.respData.type} ${router.name}(
        <#assign x>
            <#if router.pathParams??>
                <#list router.pathParams as pathParam>
                    @Parameter(description = "${pathParam.description!""}") <#if pathParam.required>@PathVariable("${pathParam.name}")<#else>@PathVariable(value="${pathParam.name}", required=false)</#if> ${pathParam.type} ${pathParam.name},
                </#list>
            </#if>
            <#if router.queryParams??>
                <#list router.queryParams as queryParam>
                    @Parameter(description = "${queryParam.description!""}") <#if queryParam.required>@RequestParam("${queryParam.requestParam}")<#elseif queryParam.defaultValue??>@RequestParam(value="${queryParam.requestParam}", required=false, defaultValue="${queryParam.defaultValue}")<#else>@RequestParam(value="${queryParam.requestParam}", required=false)</#if> ${queryParam.type} ${queryParam.name},
                </#list>
            </#if>
            <#if router.reqBody??>
                <#if router.reqBody.required>@RequestBody<#else>@RequestBody(required=false)</#if> ${router.reqBody.type} ${router.reqBody.name},
            </#if>
            <#if router.file??>
                @Parameter(description = "${router.file.description!""}") <#if router.file.required>@RequestPart("${router.file.name}")<#else>@RequestPart(value="${router.file.name}", required=false)</#if> ${router.file.type} ${router.file.name},
            </#if>
        </#assign>
        ${x?keep_before_last(",")?trim}
    );</#compress>
    <#sep>

    </#sep>
    </#list>

}
