<#if !noDefaultComment>
/**
* Code generated by unionj-generator-maven-plugin. DO NOT EDIT.
* https://github.com/unionj-cloud/unionj-generator
*/

</#if>package ${packageName};

import ${protoPackageName}.${protoName};

/**
* @ProductName: ${companyName} ${parentArtifactId}
* @Description: ${baseName}模块服务层接口类
* @Author: ${author}
* @CreateDate: ${createDate}
* @Version: ${parentVersion}
* @Copyright © ${year} ${copyright}
*/
public interface ${name} extends ${protoName} {

}
