<#if !noDefaultComment>
/**
 * Code generated by unionj-generator-maven-plugin. DO NOT EDIT.
 * https://github.com/unionj-cloud/unionj-generator
*/

</#if>package ${packageName};

import ${protoPackageName}.${protoName};

/**
 * @ProductName: ${companyName} ${parentArtifactId} <br>
 * @Description: ${baseName}模块服务层接口类 <br>
 * @Author: ${author} <br>
 * @CreateDate: ${createDate} <br>
 * @Version: ${parentVersion} <br>
 * @Copyright © ${year} ${copyright} <br>
*/
public interface ${name} extends ${protoName} {

}
