/**
* Code generated by unionj-generator-maven-plugin. DO NOT EDIT.
* https://github.com/unionj-cloud/unionj-generator
*/

package ${packageName};

import ${protoPackageName}.${protoName};

public interface ${name} extends ${protoName} {

}
