<template>
  <div class="content">
    <div class="brief">
      <h2>{{ msg }}</h2>
      <p>
        This vue project is a scaffolding generated by <a href="https://github.com/Tsingxiao/unionj-generator">unionj-generator</a> tool with openapi3
        json file as input.
      </p>
    </div>
    <div class="content">
      <h3>Feature</h3>
      <ul>
        <li>Local openapi3 api documentation support by <a href="https://github.com/Mermade/widdershins">widdershins</a> + <a href="https://github.com/Mermade/shins">shins</a></li>
        <li>Mocking rest api support by generated <a href="https://github.com/mswjs/msw">Mswjs</a> handlers</li>
        <li>
          Services with strong-typed path/query parameters, request body and
          response data
        </li>
        <li>Typescript support</li>
        <li>Ant design vue component library</li>
        <li>Axios ajax client built-in</li>
        <li>Vue router support</li>
        <li>Vuex support</li>
      </ul>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import PetService from "@/services/PetService";

export default Vue.extend({
  name: "HelloWorld",
  props: {
    msg: String,
  },
  mounted() {
    const petService = new PetService(this.$http);
    petService.getPetFindbystatus("pending").then((resp) => {
      console.log(resp);
    });
  },
});
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="less">
.content {
  width: 600px;
  margin: 0 auto;

  .brief {
    margin-bottom: 20px;
  }
  .brief p {
    text-align: left;
    font-size: 16px;
  }
  li {
    text-align: left;
    font-size: 16px;
  }
}
</style>
