/**
* Generated by unionj-generator.
* Don't edit!
* @module types
*/

<#list types as type>
    <#if type.doc??>
/**
* ${type.doc}
*/
    </#if>
export interface ${type.name} {
<#list type.properties as property>
    <#if property.doc??>
    /**
    * ${property.doc}
    */
    </#if>
    ${property.name}<#if !property.required>?</#if>: ${property.type};
</#list>
}

<#if type.enumTypes?has_content>
<#list type.enumTypes as enumType>
export enum ${enumType.name} {
<#if enumType.enums?has_content>
<#list enumType.enums as enum>
    ${enum.name} = "${enum.value}",
</#list>
</#if>
}
</#list>
</#if>

</#list>
